### ISSUE TITLE
Unable to install requirements due to dependency conflicts

### ISSUE THREAD

**Issue by tjk176** [epiccoleman/scrapio#1]
The conflict is caused by:
    The user requested jsonschema==4.19.2
    aider-chat 0.17.0 depends on jsonschema==4.19.2
    poetry 1.6.1 depends on jsonschema<4.18.0 and >=4.10.0

**Comment by epiccoleman** [comment]
Ah - looks like when I froze my requirements I was using my global python env instead of the specific venv for this project. I've changed the requirements file to fix this in the latest commit, should work for you now. Closing this as resolved, but feel free to open a new issue if you're still having trouble.
